- name: add universe repository for bionic
  become: true
  apt_repository: 
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe
    state: present
    
- name: Install dependencies for jupyter
  apt:
   name: ['python3-pip']
   state: present
   
- name: Download bioexcel github  
  become: true
  git: >
      repo=https://github.com/bioexcel/biobb_workflows.git
      dest=/home/ubuntu/bioexcel

- name: Install jupyter in biobb environment
  become: true
  command: "{{ item }}"
  with_items:
    - bash -i /home/{{lookup('env','ANSIBLE_REMOTE_USER')}}/.bashrc && conda activate biobb 
    - pip3 install jupyter
    - cd /home/ubuntu/bioexcel
    - jupyter notebook
