- name: add universe repository for bionic
  become: true
  apt_repository: 
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe
    state: present
    
#- name: Install dependencies for jupyter
#  apt:
#   name: ['python3-pip']
#   state: present
   
- name: Download bioexcel github  
  become: true
  git: >
      repo=https://github.com/bioexcel/biobb_workflows.git
      dest=/home/ubuntu/bioexcel

- name: Install jupyter in biobb environment
  become: true
  command: "{{ item }}"
  with_items:
    - bash -i /home/{{lookup('env','ANSIBLE_REMOTE_USER')}}/.bashrc && conda activate biobb 
    - sudo apt-get install python-pip
    - pip install jupyter
    - jupyter-nbextension enable nglview --py --sys-prefix
    - cd /home/ubuntu/bioexcel
    - jupyter notebook 
