- name: add universe repository for bionic
  become: true
  apt_repository: 
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe
    state: present
    
- name: Install dependencies for jupyter
  apt:
    name: ['python3-pip']
    state: present
        
- name: Create symbolic link
  become: true
  shell: ln -s  /opt/miniconda3/bin/conda /usr/bin/conda
    
- name: Activate conda env 'biobb' and install pip
  become: true
  shell: conda activate biobb; pip install jupyter
  
