- name: add universe repository for bionic
  become: true
  apt_repository: 
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe
    state: present
    
- name: Install dependencies for jupyter
  apt:
   name: ['python3-pip']
   state: present
   
- name: Download bioexcel github  
  become: true
  git: >
      repo=https://github.com/bioexcel/biobb_workflows.git
      dest=/opt/bioexcel
     
- name: opt - rwx permission for all
  become: True
  file:
    path: /opt/
    mode: +rwx
    recurse: yes 
    
- name: Install jupyter in biobb environment
  become: true
  command: "{{ item }}"
  with_items:
    - bash -i /home/{{lookup('env','ANSIBLE_REMOTE_USER')}}/.bashrc && conda activate biobb 
    - pip3 install jupyter
    - jupyter-nbextension enable nglview --py --sys-prefix
    - cd /opt/bioexcel
    #- sudo chown -R {{lookup('env','ANSIBLE_REMOTE_USER')}}:{{lookup('env','ANSIBLE_REMOTE_USER')}} ~/.local/share/jupyter 
    - jupyter notebook --no-browser --port=8889 --allow-root 
