---
- name: Test evandam.conda
  hosts: all
  roles:
    - role: evandam.conda
  tasks:
    - name: Update conda
      conda:
        name: conda
        state: latest
        executable: usr/bin/conda
    - name: Create a conda environment
      conda:
        name: python
        version: 3.6
        environment: biobb
        state: present
    - name: Install some packages in the environment
      conda:
        name:
          - 
          - 
          - 
        environment: biobb
