---
- name: Install packages using evandam conda
  roles:
   - role: evandam.conda
  block:
    - name: Create a conda environment
      conda:
        name: python
        version: 3.6
        environment: biobb
        state: present
    - name: Install some packages in the environment
      conda:
        name:
          - biobb_common==0.1.4
          - biobb_io==0.1.4
          - biobb_model==0.1.8
          - biobb_md==0.1.5
          - nglview
          - simpletraj
          - pocl
        environment: biobb
