
- name: Install some packages in the environment
  conda:
     environment: biobb
     name:
         - biobb_common
         - biobb_io
         - biobb_model
         - biobb_md
         - nglview
         - simpletraj
         - pocl    
         
- name: Soft link for OpenCL
  become: yes
  shell: sudo ln -s /etc/OpenCL/vendors /opt/miniconda3/envs/biobb/etc/OpenCL/vendors
