   
- name: Create a conda environment
  become: true
  conda:
   name: python
   environment: biobb
   state: present

- name: Install some packages in the environment
  become: true
  shell: conda activate biobb; conda install biobb_common==0.1.4; conda install biobb_io==0.1.4;biobb_model==0.1.8; 

- name: Install some packages in the environment
  become: true
  shell: conda activate biobb; conda install biobb_md==0.1.5; conda install nglview=1.2.0; conda install simpletraj; conda install pocl;
  
- name: Soft link for OpenCL
  become: true
  shell: ln -s /etc/OpenCL/vendors /home/ubuntu/miniconda3/envs/biobb/etc/OpenCL/vendors
