---
- name: Warming up to be jupyter instance
  gather_facts: no
  hosts: instance_public_ip
  vars_prompt:
   - name: jpassword
     prompt: "What is your notebook password?"
     private: no   
  tasks:
  - include_role:
      name: 'evandam.conda'
  - include_role:
      name: 'udondan.ssh-reconnect' 
  - include_role:
      name: 'yuriyguts.jupyter'    
  - name: Initial connection block
    block:
      - name: Wait 1 minutes, but only start checking after 10 seconds
        wait_for_connection:
          delay: 10
          timeout: 60
    rescue:
      - name: Try to install python 2, when ansible is not able to connect
        raw: test -e /usr/bin/python || (apt -y update && apt install -y python)

- name: Set up conda
  hosts: instance_public_ip
  become: yes
  roles:
   #- udondan.ssh-reconnect
    - conda
    - evandam.conda
    - conda-packages
    - role: yuriyguts.jupyter
      jupyter_ip: '*'
      jupyter_port: 8888
      jupyter_plaintext_password: jupytersecret
      jupyter_daemon_enable: yes
    - jupyter  

  tasks:
    - name: Make sure the user key is authorized on the nfs-server instance
      become: yes
      authorized_key: user="{{lookup('env','ANSIBLE_REMOTE_USER')}}" key="{{lookup('env','ssh_key')}}" exclusive=no state=present

     
    
