---
- name: Warming up jupyter instance
  gather_facts: no
  hosts: instance_public_ip
  tasks:
    - name: Initial connection block
      block:
        - name: Wait 30 seconds, but only start checking after 5 seconds
          wait_for_connection:
            delay: 5
            timeout: 30
      rescue:
        - name: Try to install python 2, when ansible is not able to connect
          raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
      become: yes  


- name: Setting up Conda & Jupyter environment
  hosts: instance_public_ip
  vars:
     jupyter_plaintext_password: "{{ lookup('env','JUPYTER_PASSWORD') }}"
     ansible_user: "{{lookup('env','ANSIBLE_REMOTE_USER')}}"
  become: yes
  become_user: "{{lookup('env','ANSIBLE_REMOTE_USER')}}"
  roles:
    - conda
    - role: evandam.conda
    - biobb
    - role: jupyter

  tasks:
    - name: Make sure the user key is authorized on the Jupyter server instance
      become: yes
      authorized_key: user="{{lookup('env','ANSIBLE_REMOTE_USER')}}" key="{{lookup('env','ssh_key')}}" exclusive=no state=present

     
    
