- name: Install Conda
  block:
    - name: Download Miniconda
      get_url:
        url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /tmp/Miniconda3-latest-Linux-x86_64.sh
        checksum: md5:1c945f2b3335c7b2b15130b1b2dc5cf4
    - name: Set umask
      become: true
      shell: umask 007
    - name: Create conda folder
      become: True- name: Install Conda
  block:
    - name: Download Miniconda
      get_url:
        url: https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
        dest: /tmp/install-miniconda.sh
        checksum: md5:a946ea1d0c4a642ddf0c3a26a18bb16d
        mode: 0550
    - name: Create conda folder
      become: True
      file:
        path: /opt/miniconda3
        state: directory
        owner: ubuntu
        mode: 755
        recurse: yes
    - name: Run the installer
      shell: /tmp/install-miniconda.sh -b -u -p /opt/miniconda3
    - name: Remove the installer
      file:
        state: absent
        path: /tmp/install-miniconda.sh
    - name: Add miniconda bin to path
      become: True
      shell: echo 'export PATH=/opt/miniconda3/bin:$PATH' >> /etc/profile
    - name: conda - read permission for all
      become: True
      file:
        path: /opt/miniconda3
        mode: +r
        recurse: yes
    - name: conda - execution permission for all
      become: True
      file:
        path: /opt/miniconda3/bin
        mode: +x
        recurse: yes
      file:
        path: /home/ubuntu
        state: directory
    - name: Run the installer
      shell: /tmp/Miniconda3-latest-Linux-x86_64.sh -b -u -p /home/ubuntu
    - name: Remove the installer  
      file:
        state: absent
        path: /tmp/Miniconda3-latest-Linux-x86_64.sh
    - name: Add miniconda bin to path
      become: True
      shell: echo 'export PATH=/home/ubuntu/miniconda3/bin:$PATH' >> /etc/profile
    - name: Set umask
      become: True
      shell: umask 077
    - name: conda deactivate base environment   
      become: True
      shell: conda config --set auto_activate_base false 
