- name: Install Conda
  block:
    - name: Update system
      become: True
      shell:  sudo apt update --yes
    - name: Upgrade system
      become: True
      shell:  sudo apt upgrade --yes  
    - name: Download Miniconda
      become: True
      get_url:
        url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: ~/Miniconda3-latest-Linux-x86_64.sh
    - name: Set umask
      become: True
      shell: umask 007
    - name: Install conda
      become: True
      shell: bash Miniconda3-latest-Linux-x86_64.sh
   - name: Set umask
      become: True
      shell: umask 077
      

