- name: Install Conda
  block:
    - name: Download Miniconda
      get_url:
        url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /tmp/install-miniconda.sh
        checksum: md5:1c945f2b3335c7b2b15130b1b2dc5cf4
        mode: 0550
    - name: Create conda folder
      become: yes
      file:
        path: /opt/miniconda3
        state: directory
        owner: ubuntu
        mode: 755
        recurse: yes
    - name: Run the installer
      shell: /tmp/install-miniconda.sh -b -u -p /opt/miniconda3
    - name: Wait until the file /opt/miniconda3/bin is present before continuing
      become: yes
      wait_for:
      path: /opt/miniconda3/bin  
    - name: Remove the installer
      file:
        state: absent
        path: /tmp/install-miniconda.sh
    - name: conda - read permission for all
      become: yes
      file:
        path: /opt/miniconda3
        mode: +r
        recurse: yes
    - name: conda - execution permission for all
      become: yes
      file:
        path: /opt/miniconda3/bin
        mode: +x
        recurse: yes  
    - name: conda - execution permission for all
      become: yes
      file:
       path: /opt/miniconda3/etc
       mode: +rwx
       recurse: yes    
    - name: Create symbolic link
      become: yes
      shell: ln -s  /opt/miniconda3/bin/conda /usr/bin/conda
   
    - name: Add conda config to bashrc
      become: yes
      shell: echo ' 127.0.0.1 {{lookup('env','TF_VAR_name')}} ' >> /etc/hosts
      
    - name: Source .bashrc
      become: yes
      command: bash -i /home/{{lookup('env','ANSIBLE_REMOTE_USER')}}/.bashrc
      
    - name: Conda add channels
      become: yes
      shell: conda config --add channels defaults; conda config --add channels bioconda;conda config --add channels conda-forge
   
    - name: add universe repository for bionic
      become: yes
      apt_repository: 
       repo: deb http://archive.ubuntu.com/ubuntu bionic universe
       state: present
    
    - name: Install dependencies for jupyter
      become: yes 
      apt:
       name: ['python3-pip']
       state: present
