- name: Install Conda
  block:
    - name: Download Miniconda
      get_url:
        url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /home/ubuntu/Miniconda3-latest-Linux-x86_64.sh
        checksum: md5:1c945f2b3335c7b2b15130b1b2dc5cf4
    - name: Set umask
      become: true
      shell: umask 007
    - name: Create conda folder
      become: True
      file:
        path: /home/ubuntu/miniconda3
        state: directory
    - name: Run the installer
      shell: /tmp/Miniconda3-latest-Linux-x86_64.sh -b -u -p /home/ubuntu/miniconda3
    - name: Remove the installer  
      file:
        state: absent
        path: /home/ubuntu/Miniconda3-latest-Linux-x86_64.sh
    - name: Add miniconda bin to path
      become: True
      shell: echo 'export PATH=/home/ubuntu/miniconda3/bin:$PATH' >> /etc/profile
    - name: Set umask
      become: True
      shell: umask 077
    - name: conda deactivate base environment   
      become: True
      shell: conda config --set auto_activate_base false 
