- name: Install Conda
  block:
    - name: Download Miniconda
      get_url:
        url: https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
        dest: /tmp/install-miniconda.sh
        checksum: md5:a946ea1d0c4a642ddf0c3a26a18bb16d
        mode: 0550
    - name: Create conda folder
      become: True
      file:
        path: /opt/miniconda3
        state: directory
        owner: ubuntu
        mode: 755
        recurse: yes
    - name: Run the installer
      shell: /tmp/install-miniconda.sh -b -u -p /opt/miniconda3
    - name: Wait until the file /opt/miniconda3/bin is present before continuing
      wait_for:
      path: /opt/miniconda3/bin  
    - name: Remove the installer
      file:
        state: absent
        path: /tmp/install-miniconda.sh
    - name: Add miniconda bin to path 1
      become: True
      shell: "export PATH=/opt/miniconda3/bin:$PATH"
    #- name: Add miniconda bin to path 2
    #  become: True
    #  shell: echo 'export PATH=/opt/miniconda3/bin:$PATH' >> ~/.bashrc
    #- name: Add miniconda bin to path 3
    #  become: True
    #  shell: echo 'export PATH=/opt/miniconda3/bin:$PATH' >> /etc/profile
    - name: conda - read permission for all
      become: True
      file:
        path: /opt/miniconda3
        mode: +r
        recurse: yes
    - name: conda - execution permission for all
      become: True
      file:
        path: /opt/miniconda3/bin
        mode: +x
        recurse: yes  
    - name: Run profile
      become: True
      shell: source /etc/profile
      args:
          executable: /bin/bash 
    - name: Create symbolic link
      become: true
      shell: ln -s  /opt/miniconda3/bin/conda /usr/bin/conda
    - name: Conda add channels
      become: true
      shell: conda config --add channels defaults; conda config --add channels bioconda;conda config --add channels conda-forge
