- name: Install Conda
  block:
    - name: Update system
      shell:  sudo apt update --yes
    - name: Upgrade system
      shell:  sudo apt upgrade --yes  
    - name: Download Miniconda
      get_url:
        url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: ~/Miniconda3-latest-Linux-x86_64.sh

