---
# Jupyter
jupyter_config_filename: '{{ ansible_env.HOME }}/.jupyter/jupyter_notebook_config.py'
jupyter_ip: '0.0.0.0'
jupyter_port: 8443
jupyter_package_manager_become: yes
jupyter_certfile: '{{ ansible_env.HOME }}/openssl/mycert.pem'
jupyter_keyfile: '{{ ansible_env.HOME }}/openssl/mykey.key'

# Jupyter daemon
jupyter_daemon_enable: yes
jupyter_daemon_systemd_dir: '/usr/lib/systemd/system'
jupyter_daemon_document_root: '{{ ansible_env.HOME }}/bioexcel'
jupyter_daemon_systemd_filename: '{{ jupyter_daemon_systemd_dir }}/jupyter.service'
jupyter_daemon_pidfile: '/run/jupyter.service.pid'
jupyter_start_script_file: '{{ ansible_env.HOME }}/system_script/startJupyter.sh'


